### ISSUE TITLE
Switch to files for readiness/liveness probes

### ISSUE THREAD

**Issue by nikos912000** [ExpediaGroup/mittens#11]
**Describe the feature**

At the moment Mittens starts a web server to expose liveness/readiness endpoints.
As @worldtiki pointed out in an internal discussion, although it might be easier to use endpoints instead of files for such probes, having a web server running poses risks:
- more mem/cpu is consumed by Mittens
- it's more error-prone than having files; a file is persisted on disk and will be there whenever K8S does a liveness check against pod/that file, in contrast to an endpoint which could at any point be unavailable for all sorts of reasons.

We should start writing in files instead and we could give an option to use the web-server if someone wants to do that.

**Rational**

Explanation above.

**Example Scenario**

When running Mittens as a sidecar in K8S this will be used for readiness/liveness probes.

**Comment by worldtiki** [comment]
I know I approved the pr but I was thinking about this and I am not convinced allowing the users to specify the location of the readiness/liveness files is a good idea.
That was designed for a very specific use case: kubernetes sidecar and all the constraints associated with it.
I can't think of any other scenario where we can't either use the normal http probes or simply terminate the warmup routine after it runs.

I think we should spend some time thinking about how to make these two modes (kube vs non kube) easier to configure and use by the users and giving them a good onroad experience, rather than exposing all these options as configs.
